#!/usr/bin/env python3
"""ingest.py — Knowledge Operating System ingest pipeline.

Stdlib-only. Scans sources/ for ``::atom`` marker blocks, materializes atom
files with injected provenance, and fully rebuilds every index from entity
frontmatter.

Invariants this script enforces:
  1. Indexes are DERIVED — rebuilt from scratch each run, never appended.
  2. Every atom carries provenance (source + source_location), bidirectional.
  3. Idempotent — atoms are deduped by content hash; an unchanged source adds
     nothing on re-run.

Extraction is pluggable (see config/extractor.example.json):
  marker (default) — human-authored ``::atom`` blocks, deterministic.
  llm              — a model emits ``::atom`` blocks via a Backend:
                       cli        — shell out to ollama / claude / llm / etc.
                       http-local — POST a local model server.
                     LLM output is cached by source hash to stay idempotent.

Usage:
    python3 scripts/ingest.py [--dry-run] [--verbose]
    python3 scripts/ingest.py --extractor llm --backend cli --cmd "ollama run llama3.1"
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shlex
import subprocess
import sys
import urllib.request
from datetime import date, datetime
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths — resolved relative to repo root (parent of this script's dir).
# ---------------------------------------------------------------------------
ROOT = Path(__file__).resolve().parent.parent
SOURCES = ROOT / "sources"
ATOMS = ROOT / "atoms"
THESES = ROOT / "theses"
PROJECTS = ROOT / "projects"
INDEXES = ROOT / "indexes"
LOGS = ROOT / "logs"
CONFIG = ROOT / "config" / "extractor.json"
CACHE = ROOT / ".cache" / "extract"

GENERATED_BANNER = (
    "<!-- GENERATED by scripts/ingest.py — DO NOT EDIT. "
    "Run `python3 scripts/ingest.py` to regenerate. -->"
)

# ---------------------------------------------------------------------------
# Frontmatter: tiny YAML-subset reader/writer (no PyYAML dependency).
# Supports `key: scalar` and `key: [a, b]` flat lists — sufficient for our
# schema. Anything fancier is intentionally unsupported.
# ---------------------------------------------------------------------------
_LIST_RE = re.compile(r"^\[(.*)\]$")


def _parse_scalar(raw: str):
    raw = raw.strip()
    m = _LIST_RE.match(raw)
    if m:
        inner = m.group(1).strip()
        if not inner:
            return []
        return [_unquote(item.strip()) for item in inner.split(",")]
    return _unquote(raw)


def _unquote(s: str) -> str:
    if len(s) >= 2 and s[0] == s[-1] and s[0] in "\"'":
        return s[1:-1]
    return s


def _needs_quote(s: str) -> bool:
    return bool(s) and (s[0] in " \"'[]{}#" or s[-1] == " " or ":" in s)


def _dump_scalar(value) -> str:
    if isinstance(value, list):
        return "[" + ", ".join(_dump_scalar(v) for v in value) + "]"
    s = str(value)
    if _needs_quote(s):
        return '"' + s.replace('"', '\\"') + '"'
    return s


def parse_frontmatter(text: str) -> tuple[dict, str]:
    """Split a markdown doc into (frontmatter dict, body)."""
    if not text.startswith("---"):
        return {}, text
    parts = text.split("---", 2)
    if len(parts) < 3:
        return {}, text
    fm: dict = {}
    for line in parts[1].splitlines():
        line = line.rstrip()
        if not line or line.lstrip().startswith("#"):
            continue
        if ":" not in line:
            continue
        key, _, raw = line.partition(":")
        fm[key.strip()] = _parse_scalar(raw)
    return fm, parts[2].lstrip("\n")


def dump_frontmatter(fm: dict, body: str) -> str:
    lines = ["---"]
    for key, value in fm.items():
        lines.append(f"{key}: {_dump_scalar(value)}")
    lines.append("---")
    return "\n".join(lines) + "\n\n" + body.strip() + "\n"


# ---------------------------------------------------------------------------
# Hashing.
# ---------------------------------------------------------------------------
def _normalize(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip().lower()


def content_hash(*parts: str) -> str:
    h = hashlib.sha256()
    h.update(_normalize(" ".join(parts)).encode("utf-8"))
    return h.hexdigest()


# ---------------------------------------------------------------------------
# Extractor interface — the pluggable seam. Two extractors ship:
#   MarkerExtractor — parses human-authored ``::atom`` blocks (deterministic).
#   LLMExtractor    — asks a model to emit ``::atom`` blocks, then parses them
#                     with the SAME parser. The model is reached through a
#                     pluggable Backend (CLI subprocess or local HTTP), so any
#                     local LLM / agent / CLI command works without code change.
# ---------------------------------------------------------------------------
_ATOM_BLOCK_RE = re.compile(
    r"^::atom[ \t]*\n(.*?)\n::end[ \t]*$",
    re.DOTALL | re.MULTILINE,
)


def parse_atom_blocks(text: str) -> list[dict]:
    """Parse ``::atom ... --- ... ::end`` blocks into atom dicts.

    Header (before ``---``) is frontmatter-style key/values; everything after
    ``---`` up to ``::end`` is the atom body. Shared by every extractor so the
    marker format is the single contract between humans and models.
    """
    atoms = []
    for block in _ATOM_BLOCK_RE.findall(text):
        if "---" in block:
            header, _, body = block.partition("---")
        else:
            header, body = block, ""
        meta: dict = {}
        for line in header.splitlines():
            if ":" in line and not line.lstrip().startswith("#"):
                key, _, raw = line.partition(":")
                meta[key.strip()] = _parse_scalar(raw)
        meta["_body"] = body.strip()
        atoms.append(meta)
    return atoms


class Extractor:
    def extract(self, source_body: str) -> list[dict]:
        raise NotImplementedError


class MarkerExtractor(Extractor):
    """Parses human-authored ``::atom`` blocks from a source body."""

    def extract(self, source_body: str) -> list[dict]:
        return parse_atom_blocks(source_body)


# ---------------------------------------------------------------------------
# Backends — how an LLMExtractor reaches a model. Interface: complete(prompt)
# -> raw text. All stdlib. Add a subscription-API backend later by subclassing.
# ---------------------------------------------------------------------------
class Backend:
    def complete(self, prompt: str) -> str:
        raise NotImplementedError

    def signature(self) -> str:
        """Stable identity string — folded into the cache key so switching
        model/endpoint invalidates cached extractions."""
        return self.__class__.__name__


class CliBackend(Backend):
    """Shell out to any command; prompt on stdin, completion on stdout.

    Works with ollama (``["ollama","run","llama3.1"]``), the Claude CLI
    (``["claude","-p"]``), the ``llm`` tool, llama.cpp — anything that reads a
    prompt and prints a reply.
    """

    def __init__(self, cmd: list[str], timeout: int = 300):
        if not cmd:
            raise ValueError("cli backend needs a non-empty 'cmd'")
        self.cmd = cmd
        self.timeout = timeout

    def complete(self, prompt: str) -> str:
        proc = subprocess.run(
            self.cmd, input=prompt, capture_output=True, text=True,
            timeout=self.timeout,
        )
        if proc.returncode != 0:
            raise RuntimeError(
                f"cli backend {self.cmd!r} exited {proc.returncode}: {proc.stderr.strip()}"
            )
        return proc.stdout

    def signature(self) -> str:
        return "cli:" + " ".join(self.cmd)


class HttpLocalBackend(Backend):
    """POST to a local model server (ollama / LM Studio / llama.cpp).

    Defaults target ollama's ``/api/generate``. ``response_key`` pulls the text
    out of the JSON reply (ollama uses ``response``).
    """

    def __init__(self, url: str, model: str = "", response_key: str = "response",
                 headers: dict | None = None, timeout: int = 300):
        if not url:
            raise ValueError("http-local backend needs a 'url'")
        self.url = url
        self.model = model
        self.response_key = response_key
        self.headers = headers or {}
        self.timeout = timeout

    def complete(self, prompt: str) -> str:
        payload = {"model": self.model, "prompt": prompt, "stream": False}
        data = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(self.url, data=data, method="POST")
        req.add_header("Content-Type", "application/json")
        for k, v in self.headers.items():
            req.add_header(k, v)
        with urllib.request.urlopen(req, timeout=self.timeout) as resp:
            body = json.loads(resp.read().decode("utf-8"))
        if self.response_key not in body:
            raise RuntimeError(
                f"http-local reply missing {self.response_key!r}; got keys {list(body)}"
            )
        return body[self.response_key]

    def signature(self) -> str:
        return f"http-local:{self.url}:{self.model}"


_LLM_PROMPT = """\
You extract atomic knowledge units from a source document.

Output ONLY ::atom blocks and nothing else — no prose, no preamble. Emit one
block per smallest reusable idea. Use exactly this format:

::atom
type: <fact|insight|decision|procedure>
title: <one concise line>
tags: [kebab-case, tags]
source_location: "<section or page reference>"
confidence: <0.0-1.0>
---
<the atom body — a single self-contained idea>
::end

Source document:
---
{source}
---
"""


class LLMExtractor(Extractor):
    """Asks a model (via a Backend) to emit ``::atom`` blocks, then parses them.

    Extraction is cached by (source body + backend signature) so re-running on
    an unchanged source returns identical atoms — preserving the idempotency
    invariant despite the model's non-determinism.
    """

    def __init__(self, backend: Backend, write_cache: bool = True):
        self.backend = backend
        self.write_cache = write_cache

    def extract(self, source_body: str) -> list[dict]:
        key = content_hash(self.backend.signature(), source_body)
        cache_file = CACHE / f"{key}.json"
        if cache_file.exists():
            return json.loads(cache_file.read_text(encoding="utf-8"))

        raw = self.backend.complete(_LLM_PROMPT.format(source=source_body))
        atoms = parse_atom_blocks(raw)
        if self.write_cache:
            CACHE.mkdir(parents=True, exist_ok=True)
            cache_file.write_text(json.dumps(atoms), encoding="utf-8")
        return atoms


# ---------------------------------------------------------------------------
# Extractor construction from config file + CLI overrides.
# ---------------------------------------------------------------------------
def load_config(path: Path = CONFIG) -> dict:
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))
    return {}


def build_extractor(cfg: dict, write_cache: bool) -> Extractor:
    kind = cfg.get("extractor", "marker")
    if kind == "marker":
        return MarkerExtractor()
    if kind != "llm":
        raise SystemExit(f"unknown extractor: {kind!r} (use 'marker' or 'llm')")

    backend_kind = cfg.get("backend", "cli")
    if backend_kind == "cli":
        c = cfg.get("cli", {})
        return LLMExtractor(CliBackend(c.get("cmd", []), c.get("timeout", 300)),
                            write_cache)
    if backend_kind == "http-local":
        h = cfg.get("http", {})
        headers = dict(h.get("headers", {}))
        # Optional auth header sourced from an env var — never from the file.
        auth_env = h.get("auth_env")
        if auth_env:
            token = os.environ.get(auth_env)
            if not token:
                raise SystemExit(f"env var {auth_env} is empty (needed for auth)")
            headers[h.get("auth_header", "Authorization")] = token
        return LLMExtractor(
            HttpLocalBackend(h.get("url", ""), h.get("model", ""),
                             h.get("response_key", "response"), headers,
                             h.get("timeout", 300)),
            write_cache,
        )
    raise SystemExit(f"unknown backend: {backend_kind!r} (use 'cli' or 'http-local')")


# ---------------------------------------------------------------------------
# Entity loading (for index rebuild).
# ---------------------------------------------------------------------------
def load_entities(directory: Path) -> list[dict]:
    out = []
    if not directory.exists():
        return out
    for path in sorted(directory.glob("*.md")):
        fm, body = parse_frontmatter(path.read_text(encoding="utf-8"))
        if not fm:
            continue
        fm["_path"] = path
        fm["_body"] = body
        out.append(fm)
    return out


def _rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def _as_list(value) -> list:
    if value is None:
        return []
    return value if isinstance(value, list) else [value]


# ---------------------------------------------------------------------------
# Ingest: sources -> atom files.
# ---------------------------------------------------------------------------
def ingest_sources(extractor: Extractor, dry_run: bool, verbose: bool, log: list):
    existing_hashes = set()
    for atom in load_entities(ATOMS):
        if "hash" in atom:
            existing_hashes.add(atom["hash"])

    today = date.today().strftime("%Y%m%d")
    scanned = new = skipped = 0

    for src_path in sorted(SOURCES.glob("*.md")):
        scanned += 1
        text = src_path.read_text(encoding="utf-8")
        fm, body = parse_frontmatter(text)

        # Assign source id from content hash if missing.
        src_changed = False
        if not fm.get("id"):
            sid = content_hash(text)[:8]
            fm["id"] = f"SRC-{today}-{sid}"
            src_changed = True
        source_id = fm["id"]

        atoms = extractor.extract(body)
        back_refs = _as_list(fm.get("atoms"))

        for meta in atoms:
            title = str(meta.get("title", "")).strip()
            atom_body = meta.get("_body", "")
            h = content_hash(title, atom_body)
            if h in existing_hashes:
                skipped += 1
                continue
            existing_hashes.add(h)
            atom_id = f"ATOM-{today}-{h[:8]}"

            atom_fm = {
                "id": atom_id,
                "type": meta.get("type", "fact"),
                "title": title,
                "tags": _as_list(meta.get("tags")),
                "source": source_id,
                "source_location": meta.get("source_location", ""),
                "created": date.today().isoformat(),
                "confidence": meta.get("confidence", ""),
                "hash": h,
                "linked_theses": [],
                "linked_projects": [],
            }
            atom_path = ATOMS / f"{atom_id}.md"
            if verbose:
                action = "would create" if dry_run else "create"
                print(f"  [{action}] {atom_id}  {title!r}")
            if not dry_run:
                atom_path.write_text(
                    dump_frontmatter(atom_fm, atom_body), encoding="utf-8"
                )
            if atom_id not in back_refs:
                back_refs.append(atom_id)
            new += 1

        # Write source frontmatter back (provenance back-refs + assigned id).
        if not dry_run:
            new_atoms_field = _dump_scalar(sorted(set(back_refs)))
            if src_changed or _dump_scalar(_as_list(fm.get("atoms"))) != new_atoms_field:
                fm["atoms"] = sorted(set(back_refs))
                src_path.write_text(dump_frontmatter(fm, body), encoding="utf-8")

    log.append(f"scanned={scanned} new_atoms={new} skipped={skipped}")
    if verbose:
        print(f"\nsources scanned={scanned}  new atoms={new}  skipped(dupe)={skipped}")
    return scanned, new, skipped


# ---------------------------------------------------------------------------
# Index rebuild — full regeneration from entity frontmatter.
# ---------------------------------------------------------------------------
def _link(entity: dict) -> str:
    return f"- [[{entity.get('id', '?')}]] [{entity.get('title', entity.get('id', '?'))}]({_rel(entity['_path'])})"


def rebuild_indexes(dry_run: bool, verbose: bool):
    atoms = load_entities(ATOMS)
    theses = load_entities(THESES)
    projects = load_entities(PROJECTS)
    sources = load_entities(SOURCES)

    files: dict[str, str] = {}

    # master_index.md — everything, grouped by kind.
    lines = [GENERATED_BANNER, "", "# Master Index", ""]
    for label, group in (
        ("Sources", sources),
        ("Atoms", atoms),
        ("Theses", theses),
        ("Projects", projects),
    ):
        lines.append(f"## {label} ({len(group)})")
        lines.extend(_link(e) for e in group)
        lines.append("")
    files["master_index.md"] = "\n".join(lines)

    # topic_index.md — atoms grouped by tag.
    by_tag: dict[str, list] = {}
    for a in atoms:
        for tag in _as_list(a.get("tags")):
            by_tag.setdefault(tag, []).append(a)
    lines = [GENERATED_BANNER, "", "# Topic Index", "", "Atoms grouped by tag.", ""]
    for tag in sorted(by_tag):
        lines.append(f"## {tag} ({len(by_tag[tag])})")
        lines.extend(_link(a) for a in by_tag[tag])
        lines.append("")
    files["topic_index.md"] = "\n".join(lines)

    # source_index.md — atoms grouped under their source.
    by_source: dict[str, list] = {}
    for a in atoms:
        by_source.setdefault(str(a.get("source", "?")), []).append(a)
    src_titles = {str(s.get("id")): s for s in sources}
    lines = [GENERATED_BANNER, "", "# Source Index", "", "Atoms grouped by source.", ""]
    for sid in sorted(by_source):
        s = src_titles.get(sid)
        title = s.get("title", sid) if s else sid
        path = f" ({_rel(s['_path'])})" if s else ""
        lines.append(f"## {title} — `{sid}`{path}")
        lines.extend(_link(a) for a in by_source[sid])
        lines.append("")
    files["source_index.md"] = "\n".join(lines)

    # thesis_index.md — theses with status + supporting/contradicting links.
    lines = [GENERATED_BANNER, "", "# Thesis Index", ""]
    for t in theses:
        lines.append(
            f"## {t.get('title', t.get('id'))} — `{t.get('id')}`  "
            f"[{t.get('status', 'active')}]"
        )
        lines.append(f"Confidence: {t.get('confidence', 'n/a')}  ·  ({_rel(t['_path'])})")
        sup = _as_list(t.get("supporting_atoms"))
        con = _as_list(t.get("contradicting_atoms"))
        lines.append(f"- Supporting: {', '.join(f'[[{x}]]' for x in sup) or '—'}")
        lines.append(f"- Contradicting: {', '.join(f'[[{x}]]' for x in con) or '—'}")
        lines.append("")
    files["thesis_index.md"] = "\n".join(lines)

    # tag_index.md — vocabulary + counts.
    lines = [GENERATED_BANNER, "", "# Tag Index", "", "Tag vocabulary (kebab-case).", ""]
    for tag in sorted(by_tag):
        lines.append(f"- `{tag}` — {len(by_tag[tag])}")
    files["tag_index.md"] = "\n".join(lines) + "\n"

    for name, content in files.items():
        content = content.rstrip() + "\n"
        if verbose:
            print(f"  [{'would write' if dry_run else 'write'}] indexes/{name}")
        if not dry_run:
            (INDEXES / name).write_text(content, encoding="utf-8")


# ---------------------------------------------------------------------------
# Main.
# ---------------------------------------------------------------------------
def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="KOS ingest pipeline")
    ap.add_argument("--dry-run", action="store_true", help="report without writing")
    ap.add_argument("--verbose", action="store_true", help="per-entity output")
    ap.add_argument("--extractor", choices=["marker", "llm"],
                    help="override config: marker (default) or llm")
    ap.add_argument("--backend", choices=["cli", "http-local"],
                    help="override config: llm backend")
    ap.add_argument("--cmd", help="override cli backend command, e.g. 'ollama run llama3.1'")
    ap.add_argument("--model", help="override http-local model name")
    ap.add_argument("--config", type=Path, default=CONFIG, help="extractor config path")
    args = ap.parse_args(argv)

    cfg = load_config(args.config)
    if args.extractor:
        cfg["extractor"] = args.extractor
    if args.backend:
        cfg["backend"] = args.backend
    if args.cmd:
        cfg.setdefault("cli", {})["cmd"] = shlex.split(args.cmd)
    if args.model:
        cfg.setdefault("http", {})["model"] = args.model
    extractor = build_extractor(cfg, write_cache=not args.dry_run)

    for d in (SOURCES, ATOMS, THESES, PROJECTS, INDEXES, LOGS):
        d.mkdir(exist_ok=True)

    log: list[str] = []
    started = datetime.now()
    log.append(f"run_started={started.isoformat(timespec='seconds')}")
    if args.dry_run:
        log.append("mode=dry-run")

    log.append(f"extractor={cfg.get('extractor', 'marker')}")
    if args.verbose:
        print(f"== ingest sources (extractor={cfg.get('extractor', 'marker')}) ==")
    ingest_sources(extractor, args.dry_run, args.verbose, log)

    if args.verbose:
        print("== rebuild indexes ==")
    rebuild_indexes(args.dry_run, args.verbose)

    log.append(f"run_finished={datetime.now().isoformat(timespec='seconds')}")

    if not args.dry_run:
        run_hash = content_hash(started.isoformat(), *log)[:8]
        (LOGS / f"ingest-{started.strftime('%Y%m%dT%H%M%S')}-{run_hash}.log").write_text(
            "\n".join(log) + "\n", encoding="utf-8"
        )
    print("\n".join(log))
    return 0


if __name__ == "__main__":
    sys.exit(main())
